# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6841e95d6dbd34386ee5b63b5bdedd70f971457aa81447c5915fc053793a5ecc4d5a8f6521a4003e2380f57d067955fa3fefcf7aacbbf369760dc7edd932439

test:
  secret_key_base: b7bc87f4334ff148657cdadd70bca411b5e3a222c68dafa6a450ca98412d150ac271854b0fc17ea6d0ca29590d3e6fa7c1d4b5b12eb2a80b5280c30c8382436d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
